{{< include macros.qmd >}}

## Elementary Algebra

::: notes
Mastery of [Elementary Algebra](https://en.wikipedia.org/wiki/Elementary_algebra) (a.k.a. "College Algebra")  is a prerequisite for calculus, 
which is a prerequisite for Epi 202 and Epi 203,
which are prerequisites for this course (Epi 204).
Nevertheless, each year, 
some Epi 204 students are still uncomfortable
with algebraic manipulations of mathematical formulas.
Therefore, I include this section as a quick reference.
:::

### Equalities

:::{#thm-equal-trans}
#### Equalities are transitive

If $a=b$ and $b=c$, then $a=c$

:::

---

:::{#thm-substitution}
#### Substituting equivalent expressions

If $a = b$, then for any function $f(x)$, $f(a) = f(b)$

:::

---

### Inequalities

:::{#thm-add-ineq}

If $a<b$, then $a+c < b+c$

:::

---

:::{#thm-neg-ineq}
#### negating both sides of an inequality
If $a < b$, then: $-a > -b$

:::

---

:::{#thm-mult-ineq}
If $a < b$ and $c \geq 0$, then $ca < cb$.

:::

---

:::{#thm-negative-one}

$$-a = (-1)*a$$

:::

---

### Sums

:::{#thm-add-ident}
#### adding zero changes nothing
$$a+0=a$$
:::

---

:::{#thm-sum-symmetric}
#### Sums are symmetric

$$a+b = b+a$$

:::

---

:::{#thm-sum-assoc}
#### Sums are associative

::: notes
When summing three or more terms, the order in which you sum them does not matter:
:::

$$(a + b) + c = a + (b + c)$$

:::

---

### Products

---

:::{#thm-mult-one}
#### Multiplying by 1 changes nothing

$$a \times 1 = a$$
:::

---

:::{#thm-prod-symmetric}

#### Products are symmetric

$$a \times b = b \times a$$
:::

---

:::{#thm-prod-assoc}
#### Products are associative

$$(a \times b) \times c = a \times (b \times c)$$
:::

### Sums and products together

---

:::{#thm-mult-distr}
#### Multiplication is distributive

$$a(b+c) = ab + ac$$
:::

---

### Quotients

:::{#def-quotient}

#### Quotients, fractions, rates

::: notes
A **quotient**, **fraction**, or **rate** is a division of one quantity by another:
:::

$$\frac{a}{b}$$

::: notes
In epidemiology, rates typically have a quantity involving time or population in the denominator.

c.f. <https://en.wikipedia.org/wiki/Rate_(mathematics)>
:::

:::

:::{#def-ratio}
#### Ratios

A **ratio** is a quotient in which the numerator and denominator are measured using the same unit scales.

::: notes
c.f. <https://en.wikipedia.org/wiki/Ratio>
:::

:::

---

Additional reference: <https://en.wikipedia.org/wiki/Elementary_algebra>

---

## Exponentials and Logarithms

:::{#thm-log-prod}
#### logarithm of a product is the sum of the logs of the factors
$$
\log{a\cd b} = \log{a} + \log{b}
$$

:::

:::{#cor-log-quot}
#### logarithm of a quotient

::: notes
The logarithm of a quotient is equal to the difference of the logs of the factors:
:::

$$\log{\frac{a}{b}} = \log{a} - \log{b}$$
:::

:::{#thm-log-exp}
#### logarithm of an exponential function
$$
\log{a^b} = b \cd \log{a}
$$

:::

:::{#thm-exp-sum}
#### exponential of a sum

::: notes
The exponential of a sum is equal to the product of the exponentials of the addends:
:::

$$\exp{a+b} = \exp{a} \cd \exp{b}$$

:::

:::{#cor-exp-sum}
#### exponential of a difference

::: notes
The exponential of a difference is equal to the quotient of the exponentials of the addends:
:::

$$\exp{a-b} = \frac{\exp{a}}{\exp{b}}$$

:::

---

:::{#thm-double-exp}

#### exponential of a product

$$a^{bc} = \paren{a^b}^c = \paren{a^c}^b$$
:::

---

:::{#cor-exp-ab}

#### natural exponential of a product

$$\exp{ab} = (\exp{a})^b = (\exp{b})^a$$

:::
---

:::{#thm-log-exp}

#### exp{} and log{} are mutual inverses

$$\exp{\log{a}} = \log{\exp{a}} = a$$

:::
