
:::{#def-count}
#### Count variable

A **count variable** is a random variable whose possible values are some subset of the non-negative integers; that is, a random variable $X$ such that:

$$\rangef{X} \in \Nat$$

:::

---

::: {#exr-count-examples}
What are some examples of count variables?
:::

---

::: solution
{{< include exm-count-vars.qmd >}}
:::

---

#### Exposure magnitude

:::{#def-exposure}

##### Exposure magnitude

For many count outcomes, 
there is some sense of 
**exposure magnitude**,
**population size**,  or 
**duration of observation**.

:::

---

:::{#exr-exposure-magnitude}
What are some examples of exposure magnitudes?
:::

---

::: {.solution .smaller}

outcome                      | exposure units
-----------------------------| -------------
disease incidence            | number of individuals exposed; time at risk
car accidents                | miles driven
worksite accidents           | person-hours worked
population size              | size of habitat

: Examples of exposure units {#tbl-exposure-units}

:::

:::: notes
Exposure units are similar to 
the number of trials in a binomial distribution,
but **in non-binomial count outcomes, there can be more than one event per unit of exposure**.

We can use $t$ to represent continuous-valued exposures/observation durations, 
and $n$ to represent discrete-valued exposures.

::::

---

::: {#def-event-rate}
#### Event rate

:::: notes
For a count outcome $Y$ with exposure magnitude $t$,
the **event rate** (denoted $\lambda$) 
is defined as the mean of $Y$ divided by the the exposure magnitude. 
That is:
::::

$$\mu \eqdef \Expp[Y|T=t]$$

$$\lambda \defeq \frac{\mu}{t}$$ {#eq-def-event-rate}
:::


::: notes
Event rate is somewhat analogous to odds in binary outcome models;
it typically serves as an intermediate transformation between the mean of the outcome and the linear component of the model. 
However, in contrast with the odds function, the transformation $\lambda = \mu/t$ is *not* considered part of the Poisson model's link function, and it treats the exposure magnitude covariate differently from the other covariates.
:::

---

:::{#thm-mean-vs-event-rate}
#### Transformation function from event rate to mean

For a count variable with mean $\mu$, event rate $\lambda$, and exposure magnitude $t$:

$$\tf \mu  = \lambda \cdot t$${#eq-lambda-to-mu}

:::

---

::: solution
Start from definition of event rate and use algebra to solve for $\mu$.
:::

---

@eq-lambda-to-mu is analogous to the inverse-odds function for binary variables.

---

::: {#thm-non-exposed}
When the exposure magnitude is 0, there is no opportunity for events to occur:

$$\Expp[Y|T=0] = 0$$
:::

--- 

::: proof
$$\Expp[Y|T=0] = \lambda \cdot 0 = 0$$
:::

---

#### Probability distributions for count outcomes

- [Poisson distribution](#sec-poisson-dist)

- [Negative binomial distribution](#sec-nb-dist)
